name: Aikido Security Scan

on: [push, pull_request]

jobs:
  aikido-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Aikido Scan
        # Esta é a Action oficial e atualizada deles no marketplace
        uses: aikidosec/github-actions-workflow-action@v2.0.1
        with:
          # Aqui está o ponto chave: use o Client Secret que você gerou na tela "GH"
          aikido-api-key: ${{ secrets.AIKIDO_API_KEY }}
          fail-on-priority: 'critical'
