name: Aikido Security Scan

on: [push, pull_request]

jobs:
  aikido-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Aikido CLI
        # Instalando via npm garantimos que o binário esteja no PATH do runner
        run: npm install -g @aikido/cli

      - name: Run Scan
        env:
          # Use o Client Secret que você gerou na tela "GH"
          AIKIDO_API_KEY: ${{ secrets.AIKIDO_API_KEY }}
        run: |
          # Agora o comando 'aikido-cli' será reconhecido nativamente
          aikido-cli scan . --api-key $AIKIDO_API_KEY --fail-on critical
